#!/bin/zsh
# At the (bourne) shell prompt
FiletypeDir = "~/.dotfiles/vim/after/ftplugin"

if [ -d FiletypeDir ]; then rm -Rf FiletypeDir; fi

mkdir -p ~/.dotfiles/vim/after/ftplugin

for file in /usr/share/vim/vim80/ftplugin/*.vim
do
    ln -s ~/.dotfiles/vim/vimrc-after ~/.dotfiles/vim/after/ftplugin/`basename $file`
done
