#!/bin/zsh
# At the (bourne) shell prompt
mkdir -p ~/.dotfiles/vim/after/ftplugin
rm ~/.dotfiles/vim/after/ftplugin/*
for file in /usr/share/vim/vim80/ftplugin/*.vim
do
    ln -s ~/.dotfiles/vim/vimrc-after ~/.dotfiles/vim/after/ftplugin/`basename $file`
done
