"
" Get the defaults that most users want.
" source $VIMRUNTIME/defaults.vim
"
"if has("vms")
"  set nobackup		" do not keep a backup file, use versions instead
"else
"  set backup		" keep a backup file (restore to previous version)
"  if has('persistent_undo')
"    set undofile	" keep an undo file (undo changes after closing)
"  endif
"endif


" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
"if has('syntax') && has('eval')
"  packadd! matchit
"endif



" custom paths. 
set viminfo+=n$HOME/.dotfiles/vim/viminfo
set runtimepath+=$HOME/.dotfiles/vim,$HOME/.dotfiles/vim/after
" you might have to add the following dirs manually.
set directory=$HOME/.dotfiles/vim/swap//,.,/var/tmp,/tmp " removed $HOME/tmp as 3rd to last(after .)
set backupdir=$HOME/.dotfiles/vim/backup//,.,$HOME/tmp,$HOME/
set undodir=$HOME/.dotfiles/vim/undo//,.
" custom code installingen
filetype plugin indent on
syntax on
set hidden
set foldmethod=indent
set foldlevel=99

" indentation for plugin manager checking is important
if empty(glob('~/.dotfiles/vim/autoload/plug.vim'))
   silent !curl -fLo ~/.dotfiles/vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source ~/.dotfiles/vim/vimrc
endif

" Airline Theme
let g:airline_powerline_fonts = 1
let g:airline_theme='deus'


""" TagList plugin:
filetype on
" (from taglist docs) taglist can find universal-ctags by setting:
" Tlist_Ctags_Cmd='path/to/binary'
"
" Auto-open at vim startup.
au BufNewFile,BufRead *.py
	\ let Tlist_Auto_Open=1

" pnadoc markdown.
augroup pandoc_syntax
	au! BufNewFile,BufFilePre,BufRead *.md set filetype=mardkown.pandoc
augroup END 


" toggle taglist with F8:
nnoremap <silent> <F8> :TlistToggle<CR>

call plug#begin('~/.dotfiles/vim/bundle')
" Plug 'junegunn/seoul256'
Plug 'vim-scripts/taglist.vim'
Plug 'vim-scripts/restore_view.vim'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
" Plug 'paroxayte/vwm.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'severin-lemaignan/vim-minimap'
Plug 'altercation/vim-colors-solarized'
call plug#end()
