# define user environemnt variables
# such as $PATH, $EDITOR, $PAGER, $ZDOTDIR

# Keep 1000 lines of history within the shell and save it to $ZDOTDIR/zhistory
SAVEHIST=1000
HISTSIZE=1000
HISTFILE="$ZDOTDIR/zhistory"
EDITOR="vim"
# spaceship prompt vars
# SPACESHIP_VI_MODE_SHOW=false

# vim initialization
export MYVIMRC="~/.dotfiles/vim/vimrc"
export VIMINIT="source $MYVIMRC"


# brightnesalias br="/home/mknw/scripts/brightness" # to be changed to script

# run gotop (will have to go in /usr/bin at some point)
# alias gotop="~/scripts/gotop -b"
#
# ssh
alias appjoast="ssh maccetto@app.joascantech.com"
alias joast="ssh maccetto@joascantech.com"
alias f-joast='ssh -t maccetto@joascantech.com ssh maccetto@app.joascantech.com'

alias ls="ls --color=auto"
# alias pleasetlmgr="sudo /usr/local/texlive/2019/bin/x86_64-linux/tlmgr" 
alias clvimswp='rm ~/.config/vim/swap/*'
alias tmux="tmux -f ~/.dotfiles/tmux/tmux.conf"
alias reload="exec /bin/zsh -l"

# # python shtuff
# export PYTHONPATH="$PYTHONPATH:~/.local/lib/python3.6/site-packages"
export VIRTUAL_ENV_DISABLE_PROMPT=1
# #
#
# Let's add texlive to the path
typeset -U path
# path=(/usr/local/texlive/2019/bin/x86_64-linux $path)
fpath=( "$ZDOTDIR/zfunctions" $fpath )
path=('~/.local/bin' $path)
