# define user environemnt variables
# such as $PATH, $EDITOR, $PAGER, $ZDOTDIR

# Keep 1000 lines of history within the shell and save it to $ZDOTDIR/zhistory
SAVEHIST=1000
HISTSIZE=1000
HISTFILE="$ZDOTDIR/zhistory"
EDITOR="vim"
# spaceship prompt vars
# SPACESHIP_VI_MODE_SHOW=false

# vim initialization
export MYVIMRC="~/.dotfiles/vim/vimrc"
export VIMINIT="source $MYVIMRC"
export ZDIR_COLORS="$HOME/.dir_colors"


# brightness alias br="/home/mknw/scripts/brightness" # to be changed to script

# run gotop (will have to go in /usr/bin at some point)
alias gotop="~/scripts/gotop -b"
#
# ssh
alias appjoast="ssh maccetto@app.joascantech.com"
alias joast="ssh maccetto@joascantech.com"
alias f-joast='ssh -t maccetto@joascantech.com ssh maccetto@app.joascantech.com'
alias spinoza="ssh accetto@login-01.spinozacentre.nl"
alias dasvu="ssh -t mao540@ssh.data.vu.nl ssh fs0.das5.cs.vu.nl"
alias das="ssh mao540@fs0.das5.cs.vu.nl"
alias dasvuy="ssh -tY mao540@ssh.data.vu.nl ssh -Y fs0.das5.cs.vu.nl"
# alias pleasetlmgr="sudo /usr/local/texlive/2019/bin/x86_64-linux/tlmgr" 
alias clvimswp='rm ~/.config/vim/swap/*'
alias tmux="tmux -f ~/.dotfiles/tmux/tmux.conf"
alias reload="exec /bin/zsh -l"
alias br="~/scripts/brightness" # takes an int argument between 0 and 30 (brightness level)
alias lastcmd="fc -n -1" # changing integer returns N last commands. Command allows editing before being issued.
alias man-flash="~/scripts/man-flashcard"
alias speaker="~/scripts/connectSpeaker.sh"
alias restartwifi='service network-manager restart'

alias ls="ls --color"
alias ll="ls -lG"
alias l.="ls -l -Ad .????*"
alias la="ls -la"
alias lst="echo 'Showing most recent ctime on top:\n------------------' && ls -lt -c" # 
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias mkdirp="mkdir -pv"
# alias diff='colordiff' # don't alias original commands. 
alias path='echo -e ${PATH//:/\\n}'

# controll cpu performance
alias listgovernors="cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors"
alias governor="cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
alias performance="echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"
alias powersave="echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"

# temporary
alias activenvtsw="source ~/.venv/tswvenv37/bin/activate"

# functions
highlight () { grep --color -E "$1|$" $2 ; }
palette() {for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done}

# # python shtuff
[[ -z $PYTHONPATH ]] && export PYTHONPATH="~/.local/lib/python3.7/site-packages:$PYTHONPATH"

export VIRTUAL_ENV_DISABLE_PROMPT=1

# enable Qt Xwayland comms.
export QT_PLATFORM_PLUGIN=xcb
# #
#
# Let's add texlive to the path
typeset -U path
fpath=( "$ZDOTDIR/zfunctions" $fpath )
path=( "$HOME/.local/bin" $path )
path=( $path "$HOME/scripts/" )
path+=/usr/local/texlive/2019/bin/x86_64-linux
# export PATH
# do we need this?
#
# functions
#
